// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSxYEYM0Exfzunq4oFKffciZIDs9S9aCE',
    appId: '1:485471339050:web:973da9218a0bbe68c13953',
    messagingSenderId: '485471339050',
    projectId: 'vinvi-hope',
    authDomain: 'vinvi-hope.firebaseapp.com',
    storageBucket: 'vinvi-hope.appspot.com',
    measurementId: 'G-VTCXY4NKZ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCkKgIFIfc47JFlWgbFXJpNoQn3CbnOjQ',
    appId: '1:485471339050:android:e1688d1a56d5130ec13953',
    messagingSenderId: '485471339050',
    projectId: 'vinvi-hope',
    storageBucket: 'vinvi-hope.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDb3rrRR7xhE28LOgGOqzKe90as-d4KKic',
    appId: '1:485471339050:ios:9e1ae4dcbbc2bd34c13953',
    messagingSenderId: '485471339050',
    projectId: 'vinvi-hope',
    storageBucket: 'vinvi-hope.appspot.com',
    iosBundleId: 'com.hope.vinvi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDb3rrRR7xhE28LOgGOqzKe90as-d4KKic',
    appId: '1:485471339050:ios:9e1ae4dcbbc2bd34c13953',
    messagingSenderId: '485471339050',
    projectId: 'vinvi-hope',
    storageBucket: 'vinvi-hope.appspot.com',
    iosBundleId: 'com.hope.vinvi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSxYEYM0Exfzunq4oFKffciZIDs9S9aCE',
    appId: '1:485471339050:web:25e2c2b5faa17917c13953',
    messagingSenderId: '485471339050',
    projectId: 'vinvi-hope',
    authDomain: 'vinvi-hope.firebaseapp.com',
    storageBucket: 'vinvi-hope.appspot.com',
    measurementId: 'G-D18E60V0GC',
  );
}
